---

- name: copy conf folder to remote server
  copy: src={{item.config_local_folder }} dest={{ item.copy_remote_folder }} owner=ubuntu group=ubuntu
  with_items: "{{ solr_collections }}"
  # when: conf_copy_and_collection_instance == "{{ hostvars[inventory_hostname]['ec2_dns_name'] }}"

