---
# tasks file for solr
- name: Install some prerequisites
  apt: name={{ item }} state=installed
  with_items:
    - rsync
    - unzip

# - name: Install jdk
#   roles:
#     role: williamyeh.oracle-java
#     java_version: 8
#     java_subversion: 66
#     java_download_path: /tmp
#     java_download_from_oracle: true
#     java_remove_download: true

- name: Download Solr version solr_version
  get_url: url={{ solr_dl_url }} dest={{ solr_archive }}

- include: user.yml

- name: Extract solr files
  unarchive: src={{ solr_archive }} dest={{ solr_home_parent }} copy=no
  sudo: True

# - name: Rename solr home
#   command: mv {{ solr_extracted }} {{ solr_home }} creates={{ solr_home }}
#   sudo: True
# 
# - name: Modify ownership of solr home
#   file: name={{ solr_home }} state=directory owner={{ solr_user }} group={{ solr_user }} recurse=yes
#   sudo: True

- name: Create Data Dir
  file: name={{ solr_data_dir }} state=directory owner={{ solr_user }} group={{ solr_user }}
  sudo: True

- name: Install the Solr instance
  command: creates=/etc/init.d/{{ solr_instance_name }} {{ solr_extracted }}/bin/{{ solr_install_service_script }} {{ solr_archive }} -d {{ solr_data_dir }} -p {{ solr_port }} -u {{ solr_user }}
  sudo: True

- name: Create cores
  command: bash -lc "{{ solr_instance_name }} create -c {{ item.core }}; cp {{ item.config_src }} {{ item.config_dest }}"
  with_items: cores_config
  sudo: True

- name: copy configs
  copy: src={{ item.config_src }} dest={{ item.config_dest }} mode="u=rw,g=r,o=r"
  with_items: cores_config
  sudo: True

- name: Start the Solr service
  service: name={{ solr_instance_name }} state=restarted args= "-m 2g"
