---

- include: zookeeper.yml
  tags:
    - zk
- include: solr.yml
  tags:
    - solr
- include: copy_collection_config.yml
  tags:
    - copy_collection_config
    - collection
    - change_replica
- include: create_collection.yml
  tags:
    - collection
- include: change_replica.yml
  when: inventory_hostname == solr_instances[0]
  tags:
    - change_replica
